import type { Metadata } from "next";
import { Delius_Swash_Caps, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { config } from "@fortawesome/fontawesome-svg-core";
import '@fortawesome/fontawesome-svg-core/styles.css'
import Link from "next/link";
import Cart from "./component/cart";
config.autoAddCss = false;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const deliusSwashCaps = Delius_Swash_Caps({
  variable: "--font-delius-swash-caps",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${deliusSwashCaps.variable} ${geistMono.variable}`}>
      <NavBar />
        {children}
      </body>
    </html>
  );
}


function NavBar(){
  return (
    <nav>
      <Link href="/" key="logo">Logo</Link>
      <Link href="/" key="home">Home</Link>
      <Link href="/login" key="login">Login</Link>
      <Cart />
    </nav>
  );
}